# Generated by Django 2.2.7 on 2019-12-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latittude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('S_ID', models.CharField(max_length=20)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('Date', models.CharField(max_length=8)),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('', '')], default='', max_length=20)),
                ('Fur', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('', '')], default='', max_length=10)),
                ('Location', models.CharField(choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('', '')], default='', max_length=20)),
                ('S_location', models.CharField(max_length=200)),
                ('Run', models.BooleanField()),
                ('Chase', models.BooleanField()),
                ('Climb', models.BooleanField()),
                ('Eat', models.BooleanField()),
                ('Forage', models.BooleanField()),
                ('Other_a', models.CharField(max_length=200)),
                ('Kuks', models.BooleanField()),
                ('Quaas', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('T_flag', models.BooleanField()),
                ('T_twitch', models.BooleanField()),
                ('Approach', models.BooleanField()),
                ('Indifferent', models.BooleanField()),
                ('Run_from', models.BooleanField()),
            ],
        ),
    ]
