# Generated by Django 2.2.7 on 2019-12-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='S_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
