# Generated by Django 2.2.7 on 2019-12-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_auto_20191201_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Latittude',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='S_ID',
            field=models.CharField(max_length=20),
        ),
    ]
