# Generated by Django 2.2.7 on 2019-12-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0003_auto_20191202_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Latittude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='S_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
