# Generated by Django 2.2.7 on 2019-12-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0004_auto_20191203_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Other_a',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='S_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
