# Generated by Django 2.2.7 on 2019-12-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0005_auto_20191204_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(),
        ),
    ]
