# Generated by Django 2.2.7 on 2019-12-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0007_auto_20191204_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Latittude',
            new_name='Latitude',
        ),
    ]
